### ISSUE TITLE
pre-commit is not working as expected.

### ISSUE THREAD

**Issue by legacyai** [commitizen-tools/commitizen#469] opened 2022-01-10 10:34 UTC
Pre-commit is skipping all commit messages. 
I am using following ```.pre-commit-config.yaml```

```
default_stages:
- commit
exclude: .git|.tox|tests|docs
fail_fast: true
repos:
- hooks:
  - id: commitizen
    stages: [commit-msg]
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.20.3
```
Any idea why so. I am not in main branch.

![image](https://user-images.githubusercontent.com/67182839/148751898-aad05453-1497-40da-a457-c9e519283d5a.png)

**Comment by Lee-W** [comment] 2022-01-17 10:16
Did you run `pre-commit install --hook-type commit-msg`?

**Comment by awmath** [comment] 2022-03-09 20:08
I can confirm that it is not working as stated in the docs (pre-commit==2.17.0, commitizen==v2.20.5)
The pre-commit hook won't be triggered (always marked as skipped). And even if it does (with `always_run: true`) it won't work as the input is missing.
This is probably caused by some changes within pre-commit it self as I can't even get the commit-msg output with a custom hook.

Workaround:
```
 - repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
        stages: [commit-msg]
        always_run: true
        args: [.git/COMMIT_EDITMSG]
```

**Comment by Lee-W** [comment] 2022-03-13 08:34
Hi @legacyai @awmath , sorry for late reply. I've tested with the following script and succeeded. could you please check whether it works for you? Thanks!

```sh
mkdir test_cz
cd test_cz
git init
touch .pre-commit-config.yaml

echo """default_stages: [push]
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
        stages: [commit-msg]
""" >> .pre-commit-config.yaml

pre-commit install --hook-type commit-msg
git add .
git commit -m "won't work"
```

**Comment by awmath** [comment] 2022-03-14 08:21
@Lee-W thanks for your answer which indeed works. The problem is `exclude: .git` which completly stops the `commit-msg` stage from working. So removing this from the global `exclude` or overriding `exclude` without the `.git` directory for the commitizen hook will fix this. 

In any case this is no problem within commitizen.

**Comment by Lee-W** [comment] 2022-03-14 23:29
I'll close this one then.

btw, may I know what would be the reason for adding `.git` to `exclude`?

**Closed by Lee-W** 2022-03-14 23:29 UTC
Labels: bug
