### ISSUE TITLE
Configuration file needs the path.

### ISSUE THREAD

**Issue by chienweiluo** [commitizen-tools/commitizen#816] opened 2023-08-18 08:34 UTC
### Type

- [x] Content inaccurate
- [X] Content missing
- [ ] Typo

### URL

https://commitizen-tools.github.io/commitizen/customization/

### Description

I am stuck in the customization message template. So I looked into the [ConfigPage](https://commitizen-tools.github.io/commitizen/config/) and the [CustomizePage](https://commitizen-tools.github.io/commitizen/customization/).

Then I create a `.cz.json` in my home directory. like the example in these pages.

```
{
  "commitizen": {
    "name": "cz_conventional_commits",
    "version": "0.1.0",
    "version_files": ["src/__version__.py", "pyproject.toml:version"],
    "style": [
      ["qmark", "fg:#ff9d00 bold"],
      ["question", "bold"],
      ["answer", "fg:#ff9d00 bold"],
      ["pointer", "fg:#ff9d00 bold"],
      ["highlighted", "fg:#ff9d00 bold"],
      ["selected", "fg:#cc5454"],
      ["separator", "fg:#cc5454"],
      ["instruction", ""],
      ["text", ""],
      ["disabled", "fg:#858585 italic"]
    ],
    "customize": {
      "message_template": "[{{change_type}}]:{% if show_message %} {{message}}{% endif %}",
      "example": "feature: this feature enable customize through config file",
      "schema": "<type>: <body>",
      "schema_pattern": "(feature|bug fix):(\\s.*)",
      "bump_pattern": "^(break|new|fix|hotfix)",
      "bump_map": {
          "break": "MAJOR",
          "new": "MINOR",
          "fix": "PATCH",
          "hotfix": "PATCH"
      },
      "change_type_order": ["BREAKING CHANGE", "feat", "fix", "refactor", "perf"],
      "info_path": "cz_customize_info.txt",
      "info": "This is customized info",
      "commit_parser": "^(?P<change_type>feature|bug fix):\\s(?P<message>.*)?",
      "changelog_pattern": "^(feature|bug fix)?(!)?",
      "change_type_map": {"feature": "Feat", "bug fix": "Fix"},
      "questions": [
          {
              "type": "list",
              "name": "change_type",
              "choices": [
                  {
                      "value": "feature",
                      "name": "feature: A new feature."
                  },
                  {
                      "value": "bug fix",
                      "name": "bug fix: A bug fix."
                  }
              ],
              "message": "Select the type of change you are committing"
          },
          {
              "type": "input",
              "name": "message",
              "message": "Body."
          },
          {
              "type": "confirm",
              "name": "show_message",
              "message": "Do you want to add body message in commit?"
          }
      ]
  }
  }
}
```

But when I `git cz` like usual doing,  it threw the error `The "path" argument must be of type string. Received undefined`.

and If I tried to use the cz_customize as the -n argument(Customization page mentioned), it threw `error: pathspec 'cz_customize' did not match any file(s) known to git`

Actually, the only thing I want to do is making the commit message 

from
"feat(scope): message"
to
"[feat] message"

thanks in advance.

**Comment by Lee-W** [comment] 2023-08-20 06:40
`undefined` looks like a JavaScripts thing. Could you please make sure you're using python commitizen again? I failed to reproduce it. You can also use ` git cz version -r` to provide us with more information

**Comment by chienweiluo** [comment] 2023-08-25 19:27
sorry for the late reply.

Just tried the `git cz` &  `git cz version -r`. But this error might caused by the "path" in .cz.json. 
After I add the `"path": "zzz" in .cz.json, it throws `Could not resolve zzz. Cannot find module 'zzz'` ,this means that the config works. 
And If I delete this file. it would works as usual.

![截圖 2023-08-26 上午3 20 45](https://github.com/commitizen-tools/commitizen/assets/24422923/a07b2e48-d8cc-4215-ae43-b31da8eb440a)

**Comment by Lee-W** [comment] 2023-08-26 05:09
I think what you're using is https://github.com/commitizen/cz-cli instead of this project. I'll close it for now. But feel free to reopen it if you think there's more to discuss 🙂

**Closed** 2023-08-26 05:09 UTC
Labels: pr-status: wait-for-response

**Comment by chienweiluo** [comment] 2023-08-26 14:05
okay. sorry for the misleading. I've accomplished my deal by customizing [git-cz](https://github.com/streamich/git-cz). thanks for the response.
