### ISSUE TITLE
[Feature Request] Limit any commit line to 100 characters

### ISSUE THREAD

**Issue by jtpavlock** [commitizen-tools/commitizen#224] opened 2020-07-23 01:05 UTC
## Description
Currently, [AngularJS limits their commit lines to 100 characters max.](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)

Is there any plan to also enforce this?

## Possible Solution
Return an error if the user attempts to commit a line longer than 100 characters.

**Comment by Woile** [comment] 2020-07-23 08:39
Duplicate of #191. Le's continue the discussion over there :pray:

**Closed by Woile** 2020-07-23 08:39 UTC
